import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useProfile } from '@/features/users/hooks/useProfile'
import { adminService } from '../services/adminService'

export function AdminPage() {
  const { profile, isLoading: profileLoading } = useProfile()
  const queryClient = useQueryClient()
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: adminService.overview, enabled: Boolean(profile?.is_platform_admin) })
  const [tab, setTab] = useState<'users' | 'companies' | 'catalog'>('users')
  const [message, setMessage] = useState<string | null>(null)
  const [regulation, setRegulation] = useState({ code: '', name: '', entity: '' })
  const [checklist, setChecklist] = useState({ regulationId: '', name: '', description: '', items: '' })
  const [form, setForm] = useState({ regulationId: '', name: '', type: '', description: '', fields: '' })
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['admin-overview'] })
  const suspension = useMutation({ mutationFn: ({ id, value }: { id: string; value: boolean }) => adminService.suspend(id, value), onSuccess: () => void refresh() })
  const createRegulation = useMutation({ mutationFn: adminService.createRegulation, onSuccess: () => { setRegulation({ code: '', name: '', entity: '' }); setMessage('Normativa creada'); void refresh() } })
  const createChecklist = useMutation({ mutationFn: adminService.createChecklist, onSuccess: () => { setChecklist({ regulationId: '', name: '', description: '', items: '' }); setMessage('Checklist creado'); void queryClient.invalidateQueries({ queryKey: ['checklist-catalog'] }) } })
  const createForm = useMutation({ mutationFn: adminService.createForm, onSuccess: () => { setForm({ regulationId: '', name: '', type: '', description: '', fields: '' }); setMessage('Formulario creado'); void queryClient.invalidateQueries({ queryKey: ['regulatory-forms'] }) } })

  const resetPassword = async (id: string, email: string) => {
    const temporaryPassword = window.prompt(`Contraseña temporal para ${email} (mínimo 10 caracteres)`)
    if (!temporaryPassword) return
    try { await adminService.resetPassword(id, temporaryPassword); setMessage(`Contraseña temporal asignada a ${email}. Compártela por un canal seguro.`) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo restablecer') }
  }
  const parseLines = (value: string) => value.split('\n').map((line) => line.trim()).filter(Boolean)

  if (profileLoading) return null
  if (!profile?.is_platform_admin) return <div className="py-20 text-center"><h1 className="text-xl font-semibold text-white">Acceso restringido</h1><p className="mt-2 text-gray-500">Esta sección requiere permisos de administrador de plataforma.</p></div>
  if (overview.isLoading) return <div className="flex justify-center py-24"><div className="h-10 w-10 animate-spin rounded-full border-2 border-primary-500 border-t-transparent" /></div>
  if (!overview.data) return <div className="text-red-400">No se pudo cargar la administración.</div>
  const inputClass = 'mt-1 w-full rounded-lg border border-gray-700 bg-dark-800 px-3 py-2 text-sm text-white'

  return <div className="space-y-7"><header><Link to="/dashboard" className="text-sm text-primary-400">← Dashboard</Link><h1 className="mt-3 text-2xl font-bold text-white">Administración de ADOC</h1><p className="mt-1 text-gray-400">Usuarios, empresas y catálogo normativo.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries({ Usuarios: overview.data.stats.users, Empresas: overview.data.stats.companies, 'Acciones activas': overview.data.stats.activeActions, 'Formularios enviados': overview.data.stats.submittedForms }).map(([label, value]) => <article key={label} className="rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><p className="text-sm text-gray-500">{label}</p><strong className="mt-2 block text-3xl text-primary-400">{value}</strong></article>)}</section>
    {message && <div className="rounded-xl border border-primary-500/30 bg-primary-500/10 p-3 text-sm text-primary-300">{message}</div>}
    <div className="flex gap-2">{(['users', 'companies', 'catalog'] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-3 py-2 text-sm ${tab === value ? 'bg-primary-500/15 text-primary-400' : 'text-gray-500'}`}>{value === 'users' ? 'Usuarios' : value === 'companies' ? 'Empresas' : 'Catálogo'}</button>)}</div>
    {tab === 'users' && <section className="rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><div className="divide-y divide-gray-800">{overview.data.users.map((user) => <div key={user.id} className="flex flex-col justify-between gap-3 py-4 lg:flex-row lg:items-center"><div><p className="text-sm font-medium text-white">{user.full_name || user.email}{user.is_platform_admin ? <span className="ml-2 text-xs text-primary-400">ADMIN</span> : null}</p><p className="text-xs text-gray-500">{user.email} · {user.company_name || 'Sin empresa'} · {user.role}</p></div><div className="flex gap-2"><button onClick={() => void resetPassword(user.id, user.email)} className="rounded-lg border border-gray-700 px-3 py-2 text-xs text-gray-300">Contraseña manual</button><button disabled={Boolean(user.is_platform_admin) || suspension.isPending} onClick={() => suspension.mutate({ id: user.id, value: !user.suspended_at })} className={`rounded-lg px-3 py-2 text-xs ${user.suspended_at ? 'bg-emerald-500/10 text-emerald-300' : 'bg-red-500/10 text-red-300'} disabled:opacity-40`}>{user.suspended_at ? 'Reactivar' : 'Suspender'}</button></div></div>)}</div></section>}
    {tab === 'companies' && <section className="grid gap-4 md:grid-cols-2">{overview.data.companies.map((company) => <article key={company.id} className="rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><h2 className="font-semibold text-white">{company.name}</h2><p className="mt-1 text-sm text-gray-500">NIT: {company.nit || 'Sin registrar'} · {company.member_count} miembro(s)</p></article>)}</section>}
    {tab === 'catalog' && <div className="grid gap-5 xl:grid-cols-3">
      <form onSubmit={(event) => { event.preventDefault(); createRegulation.mutate(regulation) }} className="space-y-3 rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><h2 className="font-semibold text-white">Nueva normativa</h2><label className="text-sm text-gray-400">Código<input required value={regulation.code} onChange={(event) => setRegulation({ ...regulation, code: event.target.value })} className={inputClass} /></label><label className="text-sm text-gray-400">Nombre<input required value={regulation.name} onChange={(event) => setRegulation({ ...regulation, name: event.target.value })} className={inputClass} /></label><label className="text-sm text-gray-400">Entidad<input value={regulation.entity} onChange={(event) => setRegulation({ ...regulation, entity: event.target.value })} className={inputClass} /></label><button className="rounded-lg bg-primary-500 px-4 py-2 text-sm font-semibold text-dark-950">Crear normativa</button></form>
      <form onSubmit={(event) => { event.preventDefault(); createChecklist.mutate({ ...checklist, items: parseLines(checklist.items).map((title) => ({ title })) }) }} className="space-y-3 rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><h2 className="font-semibold text-white">Nuevo checklist</h2><select required value={checklist.regulationId} onChange={(event) => setChecklist({ ...checklist, regulationId: event.target.value })} className={inputClass}><option value="">Normativa</option>{overview.data.regulations.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select><input required placeholder="Nombre" value={checklist.name} onChange={(event) => setChecklist({ ...checklist, name: event.target.value })} className={inputClass} /><textarea required rows={5} placeholder="Un requisito por línea" value={checklist.items} onChange={(event) => setChecklist({ ...checklist, items: event.target.value })} className={inputClass} /><button className="rounded-lg bg-primary-500 px-4 py-2 text-sm font-semibold text-dark-950">Crear checklist</button></form>
      <form onSubmit={(event) => { event.preventDefault(); createForm.mutate({ ...form, regulationId: form.regulationId || undefined, fields: parseLines(form.fields).map((label, index) => ({ name: `field_${index + 1}`, label, type: 'text', required: true })) }) }} className="space-y-3 rounded-2xl border border-gray-800 bg-dark-900/50 p-5"><h2 className="font-semibold text-white">Nuevo formulario</h2><select value={form.regulationId} onChange={(event) => setForm({ ...form, regulationId: event.target.value })} className={inputClass}><option value="">Sin normativa</option>{overview.data.regulations.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select><input required placeholder="Nombre" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={inputClass} /><input required placeholder="Tipo único (ej. auditoria_2026)" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className={inputClass} /><textarea required rows={4} placeholder="Un campo por línea" value={form.fields} onChange={(event) => setForm({ ...form, fields: event.target.value })} className={inputClass} /><button className="rounded-lg bg-primary-500 px-4 py-2 text-sm font-semibold text-dark-950">Crear formulario</button></form>
    </div>}
  </div>
}
